language: ruby

services:
  - docker

install:
  - docker build -t paciofspython deployment/docker/

script:
  # run paciofslocal, paciofsclient, paciofsserver
  - docker run --rm -it --privileged paciofspython `python3 paciofspython/paciofs/paciofslocal -h && python3 paciofspython/paciofs/paciofsclient -h && python3 paciofspython/paciofs/paciofsserver -h`
  # run local file system benchmark
  - docker run --rm -it --privileged paciofspython sh paciofspython/tests/benchmarks/test_fio.sh
  # run unit tests
  - docker run --rm -it --privileged paciofspython python3 -m unittest discover paciofspython/tests/unittests -v
  
